### ISSUE TITLE
Should we enforce pod naming conventions?

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#102]
A thought that just occurred to me, we've discussed moving the get_pod_name() function to the operator rs a couple of times I think. 
I do think this makes sense, since we are based on a common model of node, role, group, appname etc. we should be able to have a common naming scheme.

I'd even go so far as to add this to our integration tests and fail something, if any pod is created that doesn't match the specific schema (aka, someone created the name themselves instead of using the provided fn).

wdyt?

Related issues:
https://github.com/stackabletech/zookeeper-operator/issues/29
https://github.com/stackabletech/issues/issues/10

**Comment by maltesander** [comment]
Yes i like it, especially the testing part.

**Comment by lfrancke** [comment]
Closing in favor of #196
