### ISSUE TITLE
Consider giving `client` a configurable timeout value

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#147]
TODO: Is this still valid and/or can kube-rs specify a timeout now and do we already do so?

I ran some tests today with a weird network setup which basically caused my connection attempts to Kubernetes to never return anything. I think routing was borked and the configured ip was routed somewhere where someone just dropped packages... or something

This caused my test to hang and never go into the retry behavior I wanted to test. 

I probably just didn't wait long enough to hit an internal timeout in kube-rs somewhere, but to make things like this more predictable it might make sense to equip our client with a configurable timeout value after which Futures get cancelled and an error returned.

**Comment by lfrancke** [comment]
This might not be needed anymore after the operator rework

**Comment by teozkr** [comment]
The rework doesn't really change anything here.

**Comment by lfrancke** [comment]
True, but you don't use the client anymore do you? I mean "our" client.
You use kube-rs client directly, no?

**Comment by lfrancke** [comment]
@teozkr What's the status for kube-rs now? Does it now support specifying timeouts?

**Comment by lfrancke** [comment]
Replaced by stackabletech/issues#199
