### ISSUE TITLE
Investigate making the stackable k8s client "injectable"

### ISSUE THREAD

**Issue by razvan** [stackabletech/operator-rs#157]
## The problem

Currently the stackable k8s client is a hard-coded `struct` in the operator state. Problems:
- Large portions of operator code are not unit testable.
- Related maybe #147 
- Cannot have  a synchronous client if necessary.
 
## Proposed solution

Notes:
* Related discussions at kube-rs level: 
    - https://github.com/clux/kube-rs/issues/429
    - https://github.com/clux/kube-rs/pull/532
    - https://github.com/clux/kube-rs/issues/539

**Comment by lfrancke** [comment]
Not needed anymore I believe
