### ISSUE TITLE
Set log level to info by default

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/operator-rs#189]
Currently we don't initialize a default log level which means users won't see any output when starting the operators by default (or maybe only error or warn?

That's not good for usability.
We should set the log level to info by default, document the environment variables for logging and allow setting log level on the CLI

**Comment by razvan** [comment]
Apparently this is not easily possible. See : https://github.com/tokio-rs/tracing/issues/1466

**Comment by lfrancke** [comment]
Oh no :(
I haven't looked in detail yet but that's annoying.
Might need to move it out of this release but it may be worth looking into it and maybe helping upstream.

**Comment by soenkeliebau** [comment]
Bit late to the party here, sorry. 
We set the default log level to INFO in the [service file](https://github.com/stackabletech/kafka-operator/blob/main/server/packaging/rpm/SOURCES/stackable-kafka-operator-server-VERSION/usr/lib/systemd/system/stackable-kafka-operator-server.service#L11) for our operators. 
That doesn't work in all cases though, true.

Should we remove that from the service file or leave it in as a reminder that the log level can be changed here?

**Comment by lfrancke** [comment]
I don't think it hurts to leave it in, yeah.
Thanks for the information though
