### ISSUE TITLE
Problem with versioning when package/image was not found

### ISSUE THREAD

**Issue by maltesander** [stackabletech/operator-rs#214]
In the versioning module ([code](https://github.com/stackabletech/operator-rs/blob/617587e891725ec168b9258565851a180afaf2c7/src/versioning.rs#L243)) we print a warning if a new version is provided in the custom resource while up or downgrading to another version. Nothing else is done except updating the condition. 

This results in an endless loop (because no changes to current or target version in the status happen) if e.g. the provided package / image cannot be downloaded by the agent and the pod will never become ready. I am pretty sure there would be more reasons why we get stuck in that loop.

Deleting the pod will not help, because the cluster is upgrading / downgrading to the version where no package is available and is waiting for all pods to become ready (then we would set a current_version again). 

We need to add a check in there to exit that loop if nothing happens.

We could use a timeout and the lastTransitionTime from the conditions to keep track of it.

**Comment by lfrancke** [comment]
@maltesander Is this still relevant after the operator rework?

**Comment by maltesander** [comment]
No
