### ISSUE TITLE
Rethinking Controller{,Strategy,State}

### ISSUE THREAD

**Issue by teozkr** [stackabletech/operator-rs#224]
So the current implementation is kind of awkward, in a few ways:

1. It introduces an arbitrary split between an "init stage" and a "do stage" in reconciliation, where all data must be obtained in the init stage
2. Half of the "do stage" ends up just being calls to `ReconcileFunctionAction::then` (which also looks weird with where the `.await?`s end up placed in the code)
3. `ControllerStrategy::error_policy` is never called, because `controller::reconcile` applies its own error policy inline, rather than bubbling the errors up
4. Some of the "init stage" ends up being redundant, since it fetches data that the "do stage" inherently retrieves anyway

The reason for this structure (AFAIK) is to let the "do stage" short-circuit the reconciler after performing long-running tasks, so that new objects are picked up and prior steps are validated.

Instead, I think we could rethink `ReconcileFunctionAction::Done` as an `Error` case (which we can silence anyway, as we already do for some other errors), which lets us bubble it in the typical Rust fashion (just do `.await?`) while also allowing us to pass state between steps. Ideally, this should let us rip out `Controller{Strategy,State}` completely while making operators more ergonomic to write.

**Comment by lfrancke** [comment]
Closing this as we refactored the whole code
