### ISSUE TITLE
Merge typed role and rolegroup configs before converting to product-config maps

### ISSUE THREAD

**Issue by teozkr** [stackabletech/operator-rs#284]
Currently, overriding gets pretty tricky, since reasonable-looking code like this:

```rust
#[derive(Deserialize)]
struct FooConfig {
    #[serde(default = "FooConfig::default_port")]
    port: u16,
}

impl FooConfig {
    fn default_port() -> u16 {
        9191
    }
}
```

is subtly wrong, since the rolegroup's default `port` will override an explicitly specified `role`-level `port`. #282 made this somewhat worse, since it now triggers for all rolegroups (whereas previously it would only trigger for rolegroups that specified a `config:` field), but the issue was still there before.

**Comment by lfrancke** [comment]
@teozkr ping

**Comment by teozkr** [comment]
Ah sorry, @lfrancke. This is blocked on https://github.com/GREsau/schemars/pull/167, which is required in order to set up the correct type bounds in the generated schemas.

**Comment by lfrancke** [comment]
If we don't get any feedback here, is there anything we can reasonably do?
e.g. ping one last time and let him know that we'll get started on our own PR starting from his draft?
