### ISSUE TITLE
ContainerBuilder should reject illegal container names

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#292]
Currently the ContainerBuilder allows creating containers with illegal names (containing _ for example) and Kubernetes then rejects these when the pod is created.

We should add a check 

either in the [.new() ](https://github.com/stackabletech/operator-rs/blob/main/src/builder.rs#L93)function, or in the [.build()](https://github.com/stackabletech/operator-rs/blob/main/src/builder.rs#L187) function. This would probably be a breaking change as we'd need to change the return type to be a Result<>

**Comment by Pscheidl** [comment]
https://github.com/stackabletech/operator-rs/pull/443

**Comment by Pscheidl** [comment]
I think this one can be closed now @soenkeliebau .

**Comment by soenkeliebau** [comment]
Thank you very much for the contribution @Pscheidl
