### ISSUE TITLE
Github Actions setup: Bring in line with operators

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/operator-rs#323]
The operator-rs project is not using the operator-templating but there are a bunch of things in the operator templates that would make sense for operator-rs as well.

This is done when the two are in line (where it makes sense, e.g. docker build is not relevant here)

**Comment by soenkeliebau** [comment]
> I think the difference is too large for it to make sense in the templating but I'm open for suggestions

I concur, don't think there is much sense in bending the templating to accommodate the differences.
