### ISSUE TITLE
Upgrade to kube-rs 0.75.0

### ISSUE THREAD

**Issue by teozkr** [stackabletech/operator-rs#471]
See https://github.com/kube-rs/kube-rs/releases/tag/0.75.0

I expect that https://github.com/kube-rs/kube-rs/pull/956 will require some type-level trickery to get around, but other than that it should be fairly smooth.

Ideally we don't introduce a breaking change in operator-rs if possible

- [x] kube-rs bumped to 0.75.0
- [x] If breaking change in operator-rs is made, release notes contain migration strategy

**Comment by siegfriedweber** [comment]
Closed in favor of #490

**Comment by sbernauer** [comment]
@siegfriedweber what was the reason to reopen this ticket?

**Comment by siegfriedweber** [comment]
The ticket was not yet approved in the acceptance stage. Now it is and can be closed finally.

**Comment by sbernauer** [comment]
Ah sorry, didn't had a look at the Board stage....
