### ISSUE TITLE
ClusterResources should take the operator and controller names separately

### ISSUE THREAD

**Issue by teozkr** [stackabletech/operator-rs#482]
Currently, `ClusterResources` takes a single `manager` argument that must be unique per controller. [The documentation suggests identifying both the controller and operator names](https://github.com/stackabletech/operator-rs/blob/406c2fb62144e834981fdd89ed7203c10c0a9e5e/src/cluster_resources.rs#L161-L166) (`foo-operator_foo-controller`), but [in practice many single-controller operators just use the operator name](https://github.com/stackabletech/hbase-operator/pull/215/files/258ad6d44bff169f3566a9ffeccbeed980284662#diff-86a911b13abf77825206401b5fca7a0dece65999676e0ec1bf4b666e559e939aR36) (`foo-operator`).

This is not only inconsistent across the platform, but can lead to orphaned resources during upgrades that add more controllers (necessitating a switch to the expanded format). Additionally, it's generally a convention that un-namedspaced identifiers are reserved for the cluster administrators and users, third-party software should use the `ns/id` format for string keys (such as field managers or labels).

# Acceptance

- [ ] `ClusterResources::new` takes separate arguments for the operator and controller names
- [ ] `labels::get_recommended_labels` takes separate arguments for the operator and controller names
- [ ] `managed-by` labels and field managers follow the `operator/controller` format
- [ ] The documentation is amended to encourage FQDN-style operator names (for example: `zookeeper.stackable.tech` rather than `zookeeper-operator`)

**Comment by sbernauer** [comment]
Comment on the PR:
> I would combine both tickets into one PR because they create a breaking change at the same place. If we would merge this PR and not immediately the PR for https://github.com/stackabletech/operator-rs/issues/491 then we would force people to adapt their code twice. But I would also not implement https://github.com/stackabletech/operator-rs/issues/491 hastily without a thourough refinement.
