### ISSUE TITLE
Log aggregation creates duplicate "empty" log entries for products using log4j1  

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#576]
### Affected version

0.39.0

### Current and expected behavior

When gathering and forwarding logs from some products (current working theory is that the affected ones are log4j1) - ZooKeeper will be used as an example for this ticket.

The log file zookeeper writes looks like this:

```xml
<log4j:event logger="org.apache.zookeeper.server.NettyServerCnxn"
             timestamp="1680766222102" level="INFO" thread="nioEventLoopGroup-4-5">
  <log4j:message>Processing srvr command from /127.0.0.1:55234</log4j:message>

</log4j:event>

<log4j:event logger="org.apache.zookeeper.server.NettyServerCnxn"
             timestamp="1680766223094" level="INFO" thread="nioEventLoopGroup-4-6">
  <log4j:message>Processing srvr command from /127.0.0.1:55250</log4j:message>

</log4j:event>

```

The two events shown here can be found in OpenSearch, that works nicely. However for every entry there is also a duplicate entry with a timestamp of 1970.0.0-0:0:0 being written.

This is due to the emptly line between two records being parsed as an empty record with all null fields and a timestamp of unix epoch 0 -> 1970.

### Possible solution

Log4j uses \r\n as separator between records, not inside of the records, so this could be used to correctly identiy record boundaries and ignore these duplicates.

### Would you like to work on fixing this bug?

no

**Comment by lfrancke** [comment]
This issue is still open, the linked PR is merged. I assume this can be closed?

**Comment by maltesander** [comment]
Its not rolled out in all operators yet, but yeah i think we can close.
