### ISSUE TITLE
Consider how multiple services of the same product on one node can be configured

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#6]
Currently we only cater to overriding config setting down to a specific node. In a scenario where multiple services of the same type run on the same node (example: Elasticsearch runs best with heap settings < 32gig, but the servers have 480 gig of ram, so multiple processes are started on the same node).
In that case we'd need to be able to specify different port numbers for every service - that all run on the same node.

**Comment by lfrancke** [comment]
We now have a solution for this using our role group concept
