### ISSUE TITLE
Implement Labels::try_from<&BTreeMap<_,_>>

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/operator-rs#713]
I'm trying to convert a `&BTreeMap<String,String>` into Labels.

https://github.com/stackabletech/hdfs-operator/blob/934beeaa5b5c5e85324ccf93ba4e46cef130c440/rust/operator-binary/src/pod_svc_controller.rs#L57-L67

Code with inferred types:

![Showing inferred types](https://github.com/stackabletech/operator-rs/assets/10092581/3f8c7fdc-2f5f-4f83-8754-21b265d40c83)

```
a value of type `stackable_operator::kvp::Labels` cannot be built from an iterator over elements of type `(std::string::String, std::string::String)`
the trait `FromIterator<(std::string::String, std::string::String)>` is not implemented for `stackable_operator::kvp::Labels`
the trait `FromIterator<KeyValuePair<LabelValue>>` is implemented for stackable_operator::kvp::Labels`
```

I guess we need:
- `Labels::try_from(&btree_map)` (eg: `&BTreeMap<AsRef<str>, AsRef<str>>`)
- `Iterator::collect::<Labels>()`

**Comment by Techassi** [comment]
The linked PR only party fixes this issue. Re-opening.
