### ISSUE TITLE
Support logging to file

### ISSUE THREAD

**Issue by nightkr** [stackabletech/operator-rs#795]
This is mostly for not-operators that still depend on op-rs for consistency with the rest of the platform (like the [OPA bundle builder](https://github.com/stackabletech/opa-operator/tree/a1618d5490d29841d804e9be332f1a4c829a6385/rust/bundle-builder)).

It should support rotation via https://docs.rs/tracing-appender/latest/tracing_appender/.

**Comment by NickLarsenNZ** [comment]
Just a note, we'll want to pull this functionality over to stackable-telemetry.
Nothing to do just now, but wanted to mention it.
