### ISSUE TITLE
`ClusterResources::delete_orphaned_resources` also deletes objects that are not owned directly by it

### ISSUE THREAD

**Issue by nightkr** [stackabletech/operator-rs#861]
For example:

- user creates kafka stacklet
- kafka-op creates kafka listener (which is managed by kafka-op)
- list-op creates kafka listener service (which is managed by list-op), but propagates labels from the listener
- kafka-op sees its ownership labels on the listener service and tries to delete it, starting a tug of war with list-op
- list-op sees that the service was deleted, recreates it
- rinse, repeat, ad infinitum

Arguably, this is actually two separate bugs that should both be resolved separately:
- `delete_orphaned_resources` should also do a sanity check against `owner_references` before deleting
- list-op should use its own `ClusterResources`, and overwrite the ownership labels inherited from the listener
  - https://github.com/stackabletech/listener-operator/issues/221

**Comment by lfrancke** [comment]
This is a bug that exists in a released SDP version?

**Comment by nightkr** [comment]
Yesn't. Pretty sure that it was *present* in a older versions (haven't done a deep dive, but I suspect the logic hasn't changed significantly since back in #436) but that we didn't trigger it before now (because we didn't use the features yet that made it problematic). So it was a bug in op-rs, but not in SDP.
